#!/bin/bash
set -e; set -o pipefail; source __review-shared.sh

if [[ $# -lt 1 ]]; then
	error "usage: $(basename $0) [commit from] <commit to>"
fi
from=$1
to=${2:-$(get_ref_hash HEAD)}

push_kernel_root_dir

curr_ref="$(get_curr_ref)"
do_per_commit_build kernel-config-debug $from $to
git checkout -q "${curr_ref}"
