#!/bin/bash
set -e; set -o pipefail; source __review-shared.sh

if [[ $# -lt 1 ]]; then
	error "usage: $(basename $0) [commit from] <commit to>"
fi
from=$1
to=${2:-$(get_ref_hash HEAD)}

push_kernel_root_dir

function build_for_arch()
{
	local config=$1
	local arch=$2

	if has_compiler $arch; then
		do_per_commit_build kernel-config-$config $from $to $(get_arch_make_opts $arch)
	else
		warn "Cannot find $arch cross-compiler with prefix $(get_compiler_prefix $arch), skipping"
	fi
}

curr_ref="$(get_curr_ref)"
# Check allnoconfig.
do_per_commit_build kernel-config-allno $from $to
# Check standard debug build.
do_per_commit_build kernel-config-debug $from $to
# Check rust build, also uses clang so checks stuff gcc misses.
do_per_commit_build kernel-config-rust $from $to LLVM=1
# nommu build.
build_for_arch nommu riscv
# arm64 build.
build_for_arch arm64 arm64

echo "Restoring review-config..."
clean_all_configs
review-config
echo "...done"

git checkout -q "${curr_ref}"
