#!/bin/bash
set -e; set -o pipefail; source __review-shared.sh

if [[ $# -lt 1 ]]; then
	error "usage: $(basename $0) [name]"
fi
name=$1

check_prep

tag="$(get_review_tag $name)"
clear_review_branches $name $tag
review-stop $name warn
