#!/bin/bash
set -e; set -o pipefail; source __review-shared.sh

if [[ $# -lt 1 ]]; then
	error "usage: $(basename $0) [name] <version>"
fi
name=$1
version=$2

check_prep

tag="$(get_review_tag $name)"
if ! rev_exists $tag; then
	error "review for '$name' not started"
fi

tmpdir="$(get_temp_dir)"
cleanup_dir_on_exit $tmpdir
msgid="$(get_review_msgid $name)"
mbox_path=$(retrieve_mbox $name $msgid $tmpdir)

if [[ -z "$version" ]]; then
	version="$(get_latest_revision ${mbox_path})"
fi

branch="$(get_review_branch $name $version)"
if ! rev_exists $branch; then
	error "cannot find branch '$branch'"
fi

curr_ref="$(get_curr_ref)"

# Configure and build kernel.
git checkout -q $branch
${script_dir}/hooks/kernel-config
${script_dir}/hooks/kernel-build

# check_prep put us in the root kernel directory.

build_run_vma_tests
build_mm_tests

# Run the mm tests.
fail=""
if ! run_mm_tests; then
	fail=yes
fi
git checkout -q "${curr_ref}"
if [[ -n "$fail" ]]; then
	exit 1
fi
