#!/bin/bash
set -e; set -o pipefail; source __review-shared.sh

if [[ $# -lt 1 ]]; then
	error "usage: $(basename $0) [name] <version>"
fi
name=$1
version=$2

# This is duplicated in review-check, but useful to get this done quickly first.
review-checkpatch "$name" "$version"
# Check VMA tests and mm self tests pass.
review-check-mm-tests "$name" "$version"
# Check each individual patch builds correctly.
review-check "$name" "$version"
