#!/bin/bash
set -e; set -o pipefail; source __review-shared.sh

if [[ $# -lt 1 ]]; then
	error "usage: $(basename $0) [name] <version>"
fi
name=$1
version=$2

check_prep

tag=$(get_review_tag $name)
if ! rev_exists $tag; then
	error "review for '$name' not started"
fi

msgid="$(get_review_msgid $name)"
if ! is_valid_msgid "$msgid"; then
	version=${version:-1}
fi

if [[ -z "$version" ]]; then
	tmpdir="$(get_temp_dir)"
	cleanup_dir_on_exit $tmpdir
	mbox_path=$(retrieve_mbox $name $msgid $tmpdir quiet)
	version="$(get_latest_revision ${mbox_path})"
fi

branch="$(get_review_branch $name $version)"
if ! rev_exists $branch; then
	error "Cannot find review branch '$branch' for '$name' at version $version"
fi

from=$(get_ref_hash "$tag")
to=$(get_ref_hash "$branch")

curr_ref="$(get_curr_ref)"
git checkout -q $to
git rebase --exec "git show" $from
git checkout -q "${curr_ref}"
