#!/bin/bash
set -e; set -o pipefail; source __review-shared.sh

if [[ $# -lt 1 ]]; then
	error "usage: $(basename $0) [name] <version>"
fi
name=$1
version=$2

check_prep
if ! has_review_started $name; then
	warn "review for '$name' not started"
fi

msgid="$(get_review_msgid $name)"
tmpdir="$(get_temp_dir)"
cleanup_dir_on_exit $tmpdir

mbox_path=$(retrieve_mbox $name $msgid $tmpdir quiet)

if [[ -n "$version" ]]; then
	curr_version=$version
else
	curr_version="$(get_latest_revision ${mbox_path})"
fi
if [[ ${curr_version} -eq 1 ]]; then
	error "v1, nothing to diff against"
fi
prev_version=$((${curr_version} - 1))

review_range_diff $name $name ${mbox_path} ${mbox_path} $tmpdir ${prev_version} ${curr_version}
