#!/bin/bash
set -e; set -o pipefail; source __review-shared.sh

if [[ $# -lt 1 ]]; then
	error "usage: $(basename $0) [name]"
fi
name=$1

check_prep
if ! has_review_started $name; then
	warn "review for '$name' not started"
fi

clear_review_branches $name
