#!/bin/bash
set -e; set -o pipefail; source __review-shared.sh

if [[ $# -lt 1 ]]; then
	error "usage: $(basename $0) [commit from] <commit to>"
fi
from=$1
to=${2:-$(get_ref_hash HEAD)}

push_kernel_root_dir

function do_build()
{
	git checkout -q $to
	git rebase --exec ${script_dir}/hooks/kernel-build $from
}

function do_per_commit_build()
{
	local config=$1

	echo "---- BUILDING using $config... ----"

	git checkout -q $from
	make clean
	${script_dir}/hooks/$config
	do_build

	echo "---- BUILD using $config succeeded :) ----"
}

curr_ref="$(get_curr_ref)"
do_per_commit_build kernel-config-debug
git checkout -q "${curr_ref}"
