#!/bin/bash
set -e; set -o pipefail; source __review-shared.sh

if [[ $# -lt 1 ]]; then
	error "usage: $(basename $0) [name] <version>"
fi
name=$1
version=$2

check_prep

tag="$(get_review_tag $name)"
if ! rev_exists $tag; then
	error "review for '$name' not started"
fi

# If an off-list series, we must do this manually.
msgid="$(get_review_msgid $name)"
if ! is_valid_msgid "$msgid"; then
	version=${version:-1}
	checkpatch_range_manual "$name" "$version"
	exit 0
fi

tmpdir="$(get_temp_dir)"
cleanup_dir_on_exit $tmpdir

mbox_path=$(retrieve_mbox $name $msgid $tmpdir)

# If no version specified, get latest.
if [[ -z "$version" ]]; then
	version="$(get_latest_revision ${mbox_path})"
fi

checkpatch_range "${mbox_path}" $version
