#!/bin/bash
set -e; set -o pipefail; source __review-shared.sh

# Re-enable, we want warnings to fail build.
scripts/config -e werror

# Enable kasan, kmemleak, lockdep for debugging purposes.
scripts/config -e kasan
scripts/config -e debug_kmemleak
scripts/config -e prove_locking
