#!/bin/bash
set -e; set -o pipefail; source __review-shared.sh

make $(get_arch_make_opts arm64) mrproper
vng --kconfig --arch arm64 --config ${script_dir}/hooks/extra_config 2>/dev/null

# For some reason, vng won't set these.
scripts/config -e ext4_fs
scripts/config -e ext4_use_for_ext2
# Better for development.
scripts/config -d werror

make $(get_arch_make_opts arm64) olddefconfig
