#!/bin/bash
set -e; set -o pipefail; source __review-shared.sh

vng --kconfig --config ${script_dir}/hooks/extra_config 2>/dev/null

${script_dir}/hooks/__shared_opts

if [[ -z "$__review_no_old_def_config" ]]; then
	# Get rid of annoying LTO question, we don't want it.
	make LLVM=1 olddefconfig
fi
config_disable_modules LLVM=1 $@
